### ISSUE TITLE
[Help Wanted] G-Zip piping

### ISSUE THREAD

**Issue by kyranet** [kyranet/veza#11]
### Describe the issue

Messages in veza could be heavily compressed by piping the data through g-zip, improving the message throughput and latency.

**Comment by dshubhadeep** [comment]
@kyranet You could also look into [Brotli](https://github.com/google/brotli).It seems to be faster then g-zip.
It also has a [npm lib](https://github.com/foliojs/brotli.js).

**Comment by kyranet** [comment]
And there's also [zstd](https://github.com/facebook/zstd), which claims to be faster and lighter than brotli. The compression war never ends.

Yes, a stream-like API supporting any compression system would definitely be really nice, as it would compress and send messages without blocking the event loop, but I'd like to stick with built-in libraries first.

**Comment by dshubhadeep** [comment]
Cool, that's your call.

**Comment by kyranet** [comment]
I think I'll make the compression piping an option or something, and then release `veza-zlib`, `veza-brotli`, `veza-zstd`...

I just need to have an initial implementation on this, and design-wise, I don't know what's the best way to do this without sacrificing performance.

In other news, `veza@0.6.0` uses `binaryTF`, which can be up to 60% smaller than JSON, being significantly smaller when using references of large objects, plus the new Veza headers now take 7 bytes (versus 13 bytes, that's the 54% of byte size!), so in average, messages (specially small ones), have been reduced in size by a lot.

I still want to give a shot at compression, since in very large messages, zlib can turn a 10kb message into a 2kb one (imagine brotli or zstd!), increasing throughput by many times when the messages are usually large.

**Comment by kyranet** [comment]
After testing some stuff, I think this is unnecessary since in some fast machines, Veza can transfer dozens of MB in a few milliseconds, so this would come with too much CPU overhead.

If somebody wants to do it because of any reason (messages sent between different servers), they can import binarytf, gzip/brotli/zstd it, and send it. The overhead of a second serialization is minimum since there's no data conversion for buffers.
