### ISSUE TITLE
[Help Wanted] Connection Handshake

### ISSUE THREAD

**Issue by kyranet** [kyranet/veza#17]
### Describe the proposal

Currently, Veza resolves `Node#connectTo` way early:

**Process A**:

- `NodeSocket` Calls `Socket#connect`.
- `Socket` emits private connect, resolving the internal promise.
- `NodeSocket` emits `client.ready`.
- `Node#connectTo` resolves.

**Process B**:

- `NodeServer` receives connection, creating a `NodeServerClient`.
- `NodeServerClient` listens to all internal events, sends `Identify` packet.
- `NodeServerClient` receives Process A's `NodeSocket`'s name as a response for `Identify`.
- `NodeServerClient` emits `client.identify`.

---

The ideal way is, `Node#connectTo` should send the `Identify` packet, not the `NodeServerClient`, so both ends have their respective names.

This would also remove the parameter `name` from `Node#connectTo`, as it will be retrieved from the handshake.

**Comment by cfanoulis** [comment]
I'm studying/searching for ways to implement this.

**Comment by cfanoulis** [comment]
~~Yeah im still doing this, just trying to find my way thru the spaghetti~~
