### ISSUE TITLE
Can you please unblock me from discord.js?

### ISSUE THREAD

**Issue by DaliborTrampota** [kyranet/veza#288]
I opened an "issue" on discord.js about slash command builder I've made, if something like that could be implemented in discord.js and you banned me because me and the other guy were replying to each other. Nobody else was chatting there the issue thread was pretty much dead and you had some issues. I want to report a bug for discord.js but I can't now. Either I open another github account or you can unblock me which I'd prefer. I'm sorry that you took it personally :/ I didn't mean it

**Comment by kyranet** [comment]
I didn't block you, as a matter of a fact, that's an administrator permission, which I lack of.

What happened there is that you violated Discord.js's [Code of Conduct](https://github.com/discordjs/discord.js/blob/master/.github/CODE_OF_CONDUCT.md) with [your comment](https://github.com/discordjs/discord.js/issues/5725#issuecomment-853238844), and as such, one of the organization's administrators blocked you from the repository.

If you desire to appeal this action, please bring that to the discord.js official support server.

Closing this issue as it's not related to the library.

**Comment by DaliborTrampota** [comment]
Alright, thanks :). Also sorry for opening the issue here but I didn't know why it wouldn't let me open an issue and after some time of googling I found out I might be banned and I didn't know where else to contact you or anyone really as there isn't ban appeal channel on the discord.js support server. Anyway thanks and sorry.
